SAMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out),
    path('index/', views.index, name='index'),
    path('stu_manager/', views.stu_manager, name='stu_manager'),
    path('account_manager/', views.account_manager, name='account_manager'),
    path('act_manager/', views.act_manager, name='act_manager'),
    path('create_student/', views.create_student),
    path('create_account/', views.create_account),
    path('create_activity/', views.create_activity),
    path('delete_student?id=<int:student_ID>', views.delete_student, name='delete_student'),
    path('delete_account?id=<int:account_ID>', views.delete_account, name='delete_account'),
    path('edit_account/', views.edit_account),
    path('info_edit/', views.info_edit, name="info_edit"),
    path('open_acts/', views.open_acts, name="open_acts"),
    path('enroll?act_id=<int:activity_ID>', views.enroll, name="enroll"),
    path('manual_enroll?act_id=<int:activity_ID>&stu_id=<int:student_ID>', views.manual_enroll, name="manual_enroll"),
    path('act_info?act_id=<int:activity_ID>', views.act_info, name="act_info"),
    path('edit_act?act_id=<int:activity_ID>', views.edit_act, name="edit_act"),
    path('search/', views.search, name="search"),
    path('award_give/', views.award_give, name="award_give"),
    path('shared?act_id=<int:activity_ID>', views.shared, name="shared"),
    path('any_login/', views.any_login, name="any_login"),
    path('get_report?act_id=<int:activity_ID>', views.get_report, name="get_report"),
    path('stu_info?stu_id=<int:student_ID>', views.stu_info, name="stu_info"),
    path('graph_data/', views.graph_data, name="graph_data"),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

class Student(models.Model):
    student_ID = models.BigIntegerField(unique=True, null=False, primary_key=True)
    name = models.CharField(max_length=50, default='undef', null=False)
    sex = models.BooleanField(choices=((0, '男'), (1, '女')), default=0)
    department = models.PositiveSmallIntegerField(default=0)
    major = models.CharField(max_length=50, default='undef')
    enroll_year = models.PositiveSmallIntegerField(default=0000)
    schooling_year = models.PositiveSmallIntegerField(default=4)
    entry_count = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class User(AbstractUser):
    account = models.ForeignKey(Student, on_delete=models.CASCADE, null=True)

class Activity(models.Model):
    activity_ID = models.AutoField(unique=True, null=False, primary_key=True)
    name = models.CharField(max_length=200, default='undef', null=False)
    introduction = models.CharField(max_length=300)
    organizer = models.ForeignKey(User, on_delete=models.CASCADE) #, on_delete=models.CASCADE
    create_date = models.DateTimeField(default=timezone.now)
    capacity = models.PositiveSmallIntegerField(default=20)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    entry_count = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Entrylist(models.Model):
    entry_no = models.AutoField(unique=True, null=False, primary_key=True)
    student = models.ForeignKey(Student, null=False, on_delete=models.CASCADE) #, on_delete=models.CASCADE
    activity = models.ForeignKey(Activity, null=False, on_delete=models.CASCADE) #, on_delete=models.CASCADE
    entry_date = models.DateTimeField(default=timezone.now)
    awards = models.CharField(max_length=200, null=True, blank=True, default='未设置')
    score_kind = models.CharField(max_length=100, null=True, blank=True, default='未设置')
    score = models.FloatField(default=0, null=True, blank=True)

dashboard/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse, FileResponse, StreamingHttpResponse
from django.db import models
from django.db.models import Q
from dashboard.models import User, Student, Activity, Entrylist
from django.contrib.auth.models import Group, Permission
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.utils import timezone
from django.core import serializers
import json
from openpyxl import *
import os,sys
from tempfile import NamedTemporaryFile
import codecs

login_page = 'dashboard/login.html'
account_manager_page = 'dashboard/account_manager.html'
index_page = 'dashboard/index.html'
name_or_pwd_error = '用户名或密码不正确'
user_already_exists = '用户名已存在'
warning_null_value = '用户名或密码不能为空'
sign_up_success = 'Sign up success! Please sign in.'

###Instrumental function
# 权限组的初始化
def get_or_create_group(group_name, codename_list):
    try:
        group = Group.objects.get(name=group_name)
    except Group.DoesNotExist:
        permissions = Permission.objects.filter(codename__in=codename_list)
        group = Group.objects.create(name=group_name)
        group.permissions.set(permissions)
        group.save()
    return group

# 网页显示message, 5s后跳转到red_url
def auto_red_html(message, red_url):
    return  message + \
            '<head>\
                <meta http-equiv="refresh" content="5;URL=' + red_url + '">\
            </head>\
            <body>\
                <p>5秒后自动跳转...<br>或点击\
                    <a href="' + red_url + '">此处</a>\
                直接跳转。</p>\
            </body>'

# 学生报名活动数与活动报名学生数计数更新
def entry_count_update(student, activity):
    act_count = Entrylist.objects.filter(student=student).count()
    stu_count = Entrylist.objects.filter(activity=activity).count()
    student.entry_count = act_count
    student.save()
    activity.entry_count = stu_count
    activity.save()
    return 

###
# 登录
def log_in(request):
    if request.method == 'POST':
        if request.POST:
            username = request.POST['uname']
            password = request.POST['pwd']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                #return render(request, centre_page)
                return HttpResponseRedirect(reverse('dashboard:index'))
            else:
                return render(request, login_page, {'info': name_or_pwd_error})
        else:
            return render(request, login_page, {'info': warning_null_value})
    else:
        return render(request, login_page)

# 登出
def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('dashboard:login'))

# 登录和未登录情况下不同的网站主页初始化
@login_required
def index(request):
    current_user = request.user
    if current_user.account is None:
        return HttpResponseRedirect(reverse('dashboard:open_acts'))
    else:
        scmark = 0
        thmark = 0
        student = current_user.account
        mine_entry_list = Entrylist.objects.filter(student=student)
        my_act_count = mine_entry_list.count()
        for one in mine_entry_list:
            if '第二课堂' in one.score_kind:
                scmark = scmark + one.score
            if '思想品德' in one.score_kind:
                thmark = thmark + one.score

        return render(request, 'dashboard/index.html', {'mine_entry_list': mine_entry_list, 'act_count': my_act_count, 'scmark': scmark, 'thmark': thmark })

# 学生管理页面
@login_required
@permission_required('dashboard.add_student', raise_exception=True)
def stu_manager(request):
    stus_list = Student.objects.all()
    return render(request, 'dashboard/stu_manager.html', { 'stus_list': stus_list })

# 账户管理页面
@login_required
@permission_required('dashboard.add_user', raise_exception=True)
def account_manager(request):
    accounts_list = User.objects.all()
    return render(request, 'dashboard/account_manager.html', { 'accounts_list': accounts_list })

# 活动管理页面
@login_required
@permission_required('dashboard.add_activity', raise_exception=True)
def act_manager(request):
    organizer = User.objects.get(id=request.session.get('_auth_user_id'))
    if organizer.is_superuser:
        mine_acts_list = Activity.objects.all()
    else:
        mine_acts_list = Activity.objects.filter(organizer=organizer)
    return render(request, 'dashboard/act_manager.html', { 'mine_acts_list': mine_acts_list })

# 信息修改页面
@login_required
def info_edit(request):
    return render(request, 'dashboard/info_edit.html')

# 获取公开活动
@login_required
def open_acts(request):
    open_acts_list = Activity.objects.all()
    return render(request, 'dashboard/open_acts.html', { 'open_acts_list': open_acts_list })

# 创建学生对象(自动创建对象对应账号)
@login_required
@permission_required('dashboard.add_student', raise_exception=True)
def create_student(request):
    codename_list = [ 
        'view_activity', 
        'add_entrylist', 
    ]
    normal_users_group = get_or_create_group('normal_users', codename_list)
    if request.POST:
        stu_id = request.POST['stu_id']
        stu_name = request.POST['stu_name']
        sex = request.POST['sex']
        depart = request.POST['depart']
        major = request.POST['major']
        en_year = request.POST['en_year']
        school_year = request.POST['school_year']
        username = stu_id
        password = None
        if len(stu_id) >= 6:
            password = stu_id[-6:]
        else:
            password = stu_id
        if Student.objects.filter(student_ID=stu_id).exists():
            return HttpResponse('输入的学号已存在，请检查.')
        else:
            student = Student(\
                student_ID=int(stu_id),\
                    name=stu_name,\
                        sex=int(sex),\
                            department=int(depart),\
                                major=major,\
                                    enroll_year=int(en_year),\
                                        schooling_year=int(school_year)\
                                            )
            if User.objects.filter(username=stu_id).exists():
                student.account_status = '账户冲突'
                student.save()
                return HttpResponse('学生信息创建成功, 但学生账户已经存在，无法关联账号，请检查。')
            else:
                student.save()
                new_user = User.objects.create_user(username=username, password=password, first_name=stu_name, account=student)
                new_user.save()
                normal_users_group.user_set.add(new_user)
                student.account_status = '已创建'
                student.save()
            return HttpResponse('学生信息创建成功，学生账户默认用户名为学号，默认密码为学号至少倒数六位。')
            #return render(request, centre_page, {'result_for_cs': 'Student and login account create success.username is: ' + username + ' , and password is: ' + password })
        #return render(request, centre_page, { 'result': [stu_id, stu_name, sex, depart, major, en_year, school_year] })

# 创建账号
@login_required
@permission_required('dashboard.add_user', raise_exception=True)
def create_account(request):
    # activity_admins_group = Group.objects.get_or_create(name='activity_admins', permissions=permissions)
    codename_list = [
        'add_activity', 
        'change_activity', 
        'view_activity', 
        'add_entrylist', 
        'change_entrylist', 
        'delete_entrylist', 
        'view_entrylist', 
        'view_student',
    ]
    activity_admins_group = get_or_create_group('activity_admins', codename_list)
    if request.method == 'POST':
        if request.POST:
            username = request.POST['uname']
            password = request.POST['pwd']
            if User.objects.filter(username=username).exists():
                return render(request, account_manager_page, {'info': user_already_exists})
            else:
                new_user = User.objects.create_user(username=username, password=password)
                new_user.save()
                activity_admins_group.user_set.add(new_user)
                #return render(request, sign_in_page, {'info': sign_up_success})
                return HttpResponse('账户创建成功.')
        else:
            return HttpResponse(warning_null_value)
    else:
        return render(request, account_manager_page)

# 创建活动
@login_required
@permission_required('dashboard.add_activity', raise_exception=True)
def create_activity(request):
    if request.POST:
        act_name = request.POST['act_name']
        print(act_name)
        intro = request.POST['intro']
        organizer = User.objects.get(id=request.session.get('_auth_user_id')) 
        create_date = timezone.now()
        capacity = request.POST['capacity']
        start_date = request.POST['start_date']
        end_date = request.POST['end_date']
        # if Activity.objects.filter(name=act_name).exists():
        activity = Activity(\
            name=act_name,\
                introduction=intro,\
                    organizer=organizer,\
                        create_date=create_date,\
                            capacity=int(capacity),\
                                start_date=start_date,\
                                    end_date=end_date\
                                        )
        activity.save()
        return HttpResponse('活动创建成功。')
    else:
        return HttpResponse('输入内容不能为空。')
    #return HttpResponseRedirect(reverse('dashboard:index'))
    #return render(request, centre_page, { 'result_for_ca': [act_name, intro, organizer, create_date, capacity, start_date, end_date]})

# 删除活动
@login_required
@permission_required('dashboard.delete_activity', raise_exception=True)
def delete_activity(request, activity_ID):
    act = Activity.objects.filter(activity_ID=activity_ID)
    if act.exists():
        act.delete()
    return HttpResponseRedirect(reverse('dashboard:index'))

# 删除学生对象
@login_required

dashboard/templates/dashboard/act_info.html
{% extends 'base.html' %}
{% load static %}
{% block title %}活动管理{% endblock %}
{% block extra_css %}
<link href="{% static 'dashboard/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">{% endblock %}
{% block modal %}
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">活动修改</h4>
            </div>
            <div class="modal-body">
                <div style="width:100%;padding: 10px 20px 10px 20px">
                    <form id="ea_form">
                        {% csrf_token %}
                        活动名称: <input name="act_name" type="text" value="{{ act.name }}"> <br>
                        活动简介: <br>
                        <textarea name="intro" cols="50" rows="3">{{ act.introduction }}</textarea> <br>
                        活动人数: <input name="capacity" type="number" min="1" max="99999" value="{{ act.capacity }}"> <br>
                        开始日期: <input name="start_date" type="text" id="datetimepicker0"
                            data-date-format="yyyy-mm-dd hh:ii" value="{{ act.start_date|date:'Y-m-d H:i:s' }}"> <br>
                        结束日期: <input name="end_date" type="text" id="datetimepicker1"
                            data-date-format="yyyy-mm-dd hh:ii" value="{{ act.end_date|date:'Y-m-d H:i:s' }}"> <br>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button id="ea_sub" type="button" class="btn btn-primary">确定</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">添加报名</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-6">
                        <form class="input-group" id="search">
                            {% csrf_token %}
                            <input name="search_content" type="text" class="form-control" placeholder="输入学号或姓名">
                            <span class="input-group-btn">
                                <button id="search_btn" class="btn btn-default" type="button">搜索</button>
                            </span>
                        </form><!-- /input-group -->
                    </div><!-- /.col-lg-6 -->
                    <div id="result_list">

                    </div>
                </div><!-- /.row -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <!-- <button id="en_sub" type="button" class="btn btn-primary">确定</button> -->
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="prizeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">奖项管理</h4>
            </div>
            <div class="modal-body">
                <div style="width:100%;padding: 10px 20px 10px 20px">
                    <form id="as_form">
                        {% csrf_token %}
                        <input type="hidden" name="act_id" value="{{ act.activity_ID }}">
                        活动名称: <p id="act_name"></p>
                        学生姓名: <p id="stu_name"></p>
                        学号: <p id="stu_idno"></p>
                        <input type="hidden" id="stu_id" name="stu_id" value="0">
                        班级: <p id="department"></p>
                        所获奖项: <input id="award" name="award" type="text" > <br>
                        加分类别：<input id="score_kind" name="score_kind" type="text" > <br>
                        得分：<input id="score" name="score" type="number" > <br>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button id="as_sub" type="button" class="btn btn-primary">提交</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="downModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">文件下载</h4>
                </div>
                <div class="modal-body">
                    <div class="row" >
                        <div class="col-lg-12" id="dispath">

                        </div>
                    </div><!-- /.row -->
                </div>
                <!-- <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button id="en_sub" type="button" class="btn btn-primary">确定</button>
                </div> -->
            </div>
        </div>
    </div>
{% endblock %}
{% block act_manager %}active{% endblock %}
{% block modal_button %}
{% endblock %}
{% block table_title %}
<ol class="breadcrumb">
    <li><a href="/dashboard/act_manager/">我创建的活动</a></li>
    <li><a>活动详情</a></li>
    <li><a class="active">{{ act.name }}</a></li>
</ol>
{% endblock %}
{% block font_content %}
<div>
    <ul class="list-group">
        <li class="list-group-item">
            活动名称：{{ act.name }}
        </li>
        <li class="list-group-item">
            活动简介：{% firstof act.introduction '无' %}
        </li>
        <li class="list-group-item">
            发布者：{% firstof act.organizer.first_name act.organizer.username %}
        </li>
        <li class="list-group-item">
            已报名人数/活动容量：{{ count }}/{{ act.capacity }}
        </li>
        <li class="list-group-item">
            开始日期：{{ act.start_date|date:'Y-m-d H:i:s' }}
        </li>
        <li class="list-group-item">
            结束日期：{{ act.end_date|date:'Y-m-d H:i:s' }}
        </li>
        <li class="list-group-item">
            操作：
            <a class="btn btn-default btn-xs" data-toggle="modal" data-target="#editModal">修改信息</a>
            <a class="btn btn-primary btn-xs" data-toggle="modal" data-target="#addModal">添加报名</a>
            <a class="btn btn-success btn-xs" href="{% url 'dashboard:shared' act.activity_ID %}">分享活动</a>
            <a class="btn btn-warning btn-xs" id="makeBook" data-toggle="modal" data-target="#downModal">生成报表</a>
            <a class="btn btn-danger btn-xs" href="">删除活动</a>
        </li>
    </ul>
</div>
<h4>&nbsp;&nbsp; 活动人员名单</h4>
{% endblock %}
{% block table_content %}
<thead>
    <tr>
        <th>姓名</th>
        <th>学号</th>
        <th>班级</th>
        <th>获得奖项</th>
        <th>所加分数</th>
        <th>操作</th>
    </tr>
</thead>
<tbody>
    {% if entry_list %}
    {% for entry in entry_list %}
    <tr>
        <td>{{ entry.student.name }}</td>
        <td>{{ entry.student.student_ID }}</td>
        <td>{{ entry.student.enroll_year }}级{{ entry.student.major }}{{ entry.student.department }}班</td>
        <td>{{ entry.awards }}</td>
        <td>{{ entry.score_kind }}:{{ entry.score }}</td>
        <td>
            <a class="btn btn-primary btn-xs" type="button"
            data-act_name="{{ act.name }}" 
            data-stu_name="{{ entry.student.name }}" 
            data-stu_id="{{ entry.student.student_ID }}"
            data-stu_department="{{ entry.student.enroll_year }}级{{ entry.student.major }}{{ entry.student.department }}班"
            data-award="{{ entry.awards }}"
            data-score_kind="{{ entry.score_kind }}"
            data-score="{{ entry.score }}"
            data-toggle="modal" 
            data-target="#prizeModal"
            >获奖管理</a>
            <a class="btn btn-danger btn-xs" href="#">删除</a>
        </td>
    </tr>
    {% endfor %}
    {% else %}
    <tr>
        <td>无数据</td>
    </tr>
    {% endif %}
</tbody>
{% endblock %}
{% block extra_js %}
<script src="{% static 'dashboard/javascript/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'dashboard/javascript/transf.js' %}"></script>
<script type="text/javascript">
    $('#datetimepicker0').datetimepicker();
    $('#datetimepicker1').datetimepicker();
    sub('#ea_sub', '#ea_form', "{% url 'dashboard:edit_act' act.activity_ID  %}",
        "{% url 'dashboard:act_info' act.activity_ID  %}")
    sub('#as_sub', '#as_form', "{% url 'dashboard:award_give' %}",
        "{% url 'dashboard:act_info' act.activity_ID  %}")
    $('#search_btn').click(function () {
        $.ajax({
            type: 'post',
            dataType: 'html',
            url: '/dashboard/search/',
            data: $('#search').serialize(),
            contentType: "application/x-www-form-urlencoded",
            success: function (data) {
                var dataList = JSON.parse(data)
                // alert(JSON.parse(data)[0].fields.name)
                var flag = 1
                var tableBody =
                    '<table class="table table-striped"><thead><tr><th>姓名</th><th>学号</th><th>班级</th><th>操作</th></tr></thead><tbody>'
                for (var i of dataList) {
                    var oneField = i.fields
                    var secBtn =
                        "<a type=\"button\" class=\"btn btn-primary btn-xs\" id=\"enrollButton\" data-actId=\"{{ act.activity_ID }}\" data-stuId=\"" +
                        i.pk + "\" data-num=\"" + flag +
                        "\" data-backdrop=\"'static'\" onclick=\"enroll(this)\">添加</a>"
                    tableBody = tableBody + "<tr><td>" + oneField.name + "</td><td>" + i.pk +
                        "</td><td>" + oneField.enroll_year + "级" + oneField.major + oneField
                        .department + "班" + "</td><td>" + secBtn + "</td></tr>"
                    flag++
                }
                tableBody = tableBody + "</tbody></table>"
                document.getElementById("result_list").innerHTML = tableBody
                // location.replace(rep_url)
            }
        })
    })

    function enroll(as) {
        var a = $(as)
        var stu_id = a.data("stuid")
        var act_id = a.data("actid")
        var url = "manual_enroll?act_id=" + act_id + "&stu_id=" + stu_id
        $.get(encodeURIComponent(url), function (result) {
            var result_list = document.getElementById("result_list")
            if (result == "200") {
                a.html = "已报名"
                a.attr('disabled', 'disabled')
                var sucMsg = document.createElement("div")
                sucMsg.setAttribute('class', 'alert alert-success alert-dismissible')
                sucMsg.setAttribute('role', 'alert')
                sucMsg.innerHTML = '添加成功。'
                result_list.after(sucMsg)
            } else if (result == "002") {
                // var btn = document.getElementById("enrollButton")
                a.html = "已报名"
                a.attr('disabled', 'disabled')
                var warnMsg = document.createElement("div")
                warnMsg.setAttribute('class', 'alert alert-warning alert-dismissible')
                warnMsg.setAttribute('role', 'alert')
                warnMsg.innerHTML = '对象在此之前已经被添加。'
                result_list.after(warnMsg)
            }
        });
    }
    $('#addModal').on('hidden.bs.modal', function (e) {
        window.location.reload()
    })
    $('#prizeModal').on('show.bs.modal', function (event) {
		var button = $(event.relatedTarget)
        var act_name = button.data('act_name')
        var stu_name = button.data('stu_name')
        var stu_id = button.data('stu_id')
        var stu_depart = button.data('stu_department')
        var award = button.data('award')
        var score_kind = button.data('score_kind')
		var score = button.data('score')
		var modal = $(this)
        modal.find('#act_name').text(act_name)
        modal.find('#stu_name').text(stu_name)
        modal.find('#stu_idno').text(stu_id)
        modal.find('#stu_id').val(stu_id)
        modal.find('#department').text(stu_depart)
        modal.find('#award').val(award)
        modal.find('#score_kind').val(score_kind)
        modal.find('#score').val(score)
    })
    $('#makeBook').click(function(){
        var dispath = $('#dispath')
        dispath.append('系统正在生成，请稍等...')
        $.get("{% url 'dashboard:get_report' act.activity_ID %}", function (result) {
            dispath.empty()
            dispath.append('<a href="' + result + '">' + result + '</a>')
        })
    })
    $('#downModal').on('hidden.bs.modal', function (e) {
        var dispath = $('#dispath')
        dispath.empty()
    })
</script>{% endblock %}

dashboard/templates/dashboard/open_acts.html
{% extends "base.html" %}
{% block title %}公开活动{% endblock %}
{% block modal %}
<div class="modal fade" id="checkModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span 
						aria-hidden="true">&times;</span></button>
			</div>
			<div class="modal-body">
				<div style="width:100%;padding: 10px 20px 10px 20px">
					<p>确认报名？</p>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
				<a type="button" class="btn btn-primary" href="#">确定</a>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block open_acts %}active{% endblock %}
{% block table_title %}<h3>公开的活动</h3>{% endblock %}
{% block table_content %}
<thead>
	<tr>
		<th>#</th>
		<th>活动名称</th>
		<th>活动人数</th>
		<th>开始日期</th>
		<th>结束日期</th>
		<th>操作</th>
	</tr>
</thead>
<tbody>
	{% if open_acts_list %}
	{% for act in open_acts_list %}
	<tr>
		<td>{{ act.activity_ID }}</td>
		<td>{{ act.name }}</td>
		<td>{{ act.capacity }}</td>
		<td>{{ act.start_date|date:'Y-m-d H:i:s' }}</td>
		<td>{{ act.end_date|date:'Y-m-d H:i:s' }}</td>
		<td>
			{% if user.account %}
			<button class="btn btn-primary btn-xs" style="margin-top:0" data-toggle="modal" data-target="#checkModal"
				data-enroll_url="{% url 'dashboard:enroll' act.activity_ID %}"
				data-act_name="{{ act.name }}">报名</button>
			{% endif %}
		</td>
	</tr>
	{% endfor %}
	{% else %}
	<tr>
		<td>无数据</td>
	</tr>
	{% endif %}
</tbody>
{% endblock %}
{% block extra_js %}
<script>
	$('#checkModal').on('show.bs.modal', function (event) {
		var button = $(event.relatedTarget)
		var act_name = button.data('act_name')
		var enroll_url = button.data('enroll_url')
		var modal = $(this)
		modal.find('.modal-body p').text('确认报名活动：' + act_name + ' 吗？')
		modal.find('.modal-footer a').attr('href', enroll_url)
	})
</script>
{% endblock %}